### ISSUE TITLE
FileNotFound exception when running rename.cmd

### ISSUE THREAD

**Issue by ShockDeveloper** [delegateas/XrmFramework#36]
Hi guys,

I have just cloned the project and have followed the instructions on the page but I unfortunately receive an error message when I try to use the rename.cmd file.

I am running: Visual Studio 2019 Professional

The XrmProject is stored at the path: C:\source_code\XrmFramework

Under this path is the: XrmOrg folder and the rename.cmd batch file.
(I have also checked that the FSI is located in the standard folder, which it is).

**I do the following:**
**1)** Open a cmd prompt
**2)** Write the command: cd C:\source_code\XrmFramework and press Enter
**3)** Write the command: rename.cmd comp=CompanyTest org=OrganizationTest sol=SolutionTest

**After some seconds it shows the message:**
2023-01-13T16:19:06.6100296+01:00 - Error: ([], "XrmOrg.XrmSolution", "Organization.Solution") (System.IO.FileNotFoundException: Could not find file 'C:\source_code\XrmFramework\XrmOrg\XrmOrg.XrmSolution'.
File name: 'C:\source_code\XrmFramework\XrmOrg\XrmOrg.XrmSolution'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at FSI_0001.Rename.renameFiles(String sourcePath, String targetPath) in C:\source_code\XrmFramework\rename.fsx:line 102
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in D:\a\_work\4\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\4\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in D:\a\_work\4\s\src\fsharp\FSharp.Core\seq.fs:line 729
   at FSI_0001.renameIO[a](String source, String target, FSharpFunc`2 fn, FSharpList`1 atomic') in C:\source_code\XrmFramework\rename.fsx:line 118)
Press any key to continue . . .

Is there a step I forgot or some requirements? To me, it looks like it's looking for some F sharp code at a hard-coded location (D:\a\_* ?)

**Comment by ShockDeveloper** [comment]
I have been able to perform this step on a different computer with no issues. Both before and after opening the downloaded project.
